feat: added downloadable link for attachments

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,10 @@
 echo "runnning prettier"
 
+pnpm lint || {
+  echo "lint failed"
+  exit 1
+}
+
 
 pnpm exec prettier --check . || {
   echo ""
